/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated.index'
import { Route as AuthenticatedQaRouteImport } from './routes/_authenticated.qa'
import { Route as AuthenticatedNikostartRouteImport } from './routes/_authenticated.nikostart'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedQaRoute = AuthenticatedQaRouteImport.update({
  id: '/qa',
  path: '/qa',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedNikostartRoute = AuthenticatedNikostartRouteImport.update({
  id: '/nikostart',
  path: '/nikostart',
  getParentRoute: () => AuthenticatedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/auth': typeof AuthRoute
  '/nikostart': typeof AuthenticatedNikostartRoute
  '/qa': typeof AuthenticatedQaRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/nikostart': typeof AuthenticatedNikostartRoute
  '/qa': typeof AuthenticatedQaRoute
  '/': typeof AuthenticatedIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/nikostart': typeof AuthenticatedNikostartRoute
  '/_authenticated/qa': typeof AuthenticatedQaRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/auth' | '/nikostart' | '/qa'
  fileRoutesByTo: FileRoutesByTo
  to: '/auth' | '/nikostart' | '/qa' | '/'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/nikostart'
    | '/_authenticated/qa'
    | '/_authenticated/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/qa': {
      id: '/_authenticated/qa'
      path: '/qa'
      fullPath: '/qa'
      preLoaderRoute: typeof AuthenticatedQaRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/nikostart': {
      id: '/_authenticated/nikostart'
      path: '/nikostart'
      fullPath: '/nikostart'
      preLoaderRoute: typeof AuthenticatedNikostartRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedNikostartRoute: typeof AuthenticatedNikostartRoute
  AuthenticatedQaRoute: typeof AuthenticatedQaRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedNikostartRoute: AuthenticatedNikostartRoute,
  AuthenticatedQaRoute: AuthenticatedQaRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
